version: '3.8'

services:
  api-investimentos:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:sqlite:/data/investimento.db
    volumes:
      - ./data:/data
    restart: unless-stopped